{
  "openapi": "3.0.0",
  "info": {
    "title": "API MonkeyTech v2",
    "description": "API para CRUD de produtos eletrônicos",
    "termsOfService": "",
    "contact": {
      "email": "alexneto.best@gmail.com"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000",
      "description": "API de teste"
    },
    {
      "url": "https://monkeytechv2.herokuapp.com",
      "description": "API de produção"
    }
  ],
  "paths": {
    "/produtos/todos": {
      "get": {
        "summary": "Lista de todos os Produtos",
        "description": "Rota responsável por listar todos os produtos",
        "tags": ["Produtos"],
        "responses": {
          "404": {
            "description": "Not Found"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schemas": {
                  "type": "array",
                  "items": {
                    "$ref": "#components/schemas/Produtos"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/produtos/{id}": {
      "get": {
        "summary": "Busca um produto por ID",
        "description": "Rota responsável por buscar um produto por ID",
        "tags": ["Produtos"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do produto para a busca",
            "required": true
          }
        ],
        "responses": {
          "404": {
            "description": "Not Found"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schemas": {
                  "type": "array",
                  "$ref": "#components/schemas/Produtos"
                }
              }
            }
          }
        }
      }
    },
    "/produtos/novo": {
      "post": {
        "summary": "Cadastrar um produto",
        "description": "Rota responsável por cadastrar um produto",
        "tags": ["Produtos"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Produtos"
              },
              "examples": {
                "Produtos": {
                  "value": {
                    "produto": "Novo Google Nest Audio",
                    "descricao": "Google Nest Audio com assistente virtual Google Assistente. O Google Nest vem com o Google Assistente integrado.",
                    "foto": "./assets/images/NEST.png",
                    "preco": 1249
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Bad Request"
          },
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Produtos"
                }
              }
            }
          }
        }
      }
    },
    "/produtos/mudar/{id}": {
      "put": {
        "summary": "Editar um produto pelo ID",
        "description": "Rota responsável por editar um produto pelo ID",
        "tags": ["Produtos"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do produto para a busca",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Produtos"
              },
              "examples": {
                "Produtos": {
                  "value": {
                    "produto": "Google Nest Audio Modificado",
                    "descricao": "Google Nest Audio com assistente virtual Google Assistente. O Google Nest vem com o Google Assistente integrado.",
                    "foto": "./assets/images/NEST.png",
                    "preco": 1249
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Bad Request"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Produtos"
                }
              }
            }
          }
        }
      }
    },
    "/produtos/del/{id}": {
      "delete": {
        "summary": "Apagar um produto pelo ID",
        "description": "Rota responsável por apagar um produto pelo ID",
        "tags": ["Produtos"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do produto para deleção",
            "required": true
          }
        ],
        "responses": {
          "400": {
            "description": "Bad Request"
          },
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/usuarios": {
      "get": {
        "summary": "Lista de todos os Usuários",
        "description": "Rota responsável por listar todos os usuários",
        "tags": ["Usuarios"],
        "responses": {
          "404": {
            "description": "Not Found"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schemas": {
                  "type": "array",
                  "items": {
                    "$ref": "#components/schemas/Usuarios"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/usuarios/{id}": {
      "get": {
        "summary": "Busca um usuário por ID",
        "description": "Rota responsável por buscar um usuário por ID",
        "tags": ["Usuarios"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do usuario para a busca",
            "required": true
          }
        ],
        "responses": {
          "404": {
            "description": "Not Found"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schemas": {
                  "type": "array",
                  "$ref": "#components/schemas/Usuarios"
                }
              }
            }
          }
        }
      }
    },
    "/usuarios/novo": {
      "post": {
        "summary": "Cadastrar um usuario",
        "description": "Rota responsável por cadastrar um usuario",
        "tags": ["Usuarios"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Usuarios"
              },
              "examples": {
                "Usuarios": {
                  "value": {
                    "email": "randomail@randomail.com",
                    "nome": "Random Silva",
                    "senha": "123456",
                    "adm": false
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Bad Request"
          },
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Usuarios"
                }
              }
            }
          }
        }
      }
    },
    "/usuarios/mudar/{id}": {
      "put": {
        "summary": "Editar um usuario pelo ID",
        "security": [
          {
            "token": []
          }
        ],
        "description": "Rota responsável por editar um usuario pelo ID",
        "tags": ["Usuarios"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do usuario para a busca",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Usuarios"
              },
              "examples": {
                "Usuarios": {
                  "value": {
                    "email": "randomail@randomail.com",
                    "nome": "Random da Silva",
                    "senha": "123456",
                    "adm": false
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Bad Request"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Usuarios"
                }
              }
            }
          }
        }
      }
    },
    "/usuarios/del/{id}": {
      "delete": {
        "summary": "Apagar um usuario pelo ID",
        "description": "Rota responsável por apagar um usuario pelo ID",
        "security": [
          {
            "token": []
          }
        ],
        "tags": ["Usuarios"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do usuario para deleção",
            "required": true
          }
        ],
        "responses": {
          "400": {
            "description": "Bad Request"
          },
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/login": {
      "post": {
        "summary": "Entrar na API com autenticação",
        "description": "Rota responsável por permitir acesso do usuário",
        "tags": ["Login"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Login"
              },
              "examples": {
                "Usuarios": {
                  "value": {
                    "email": "randomail@randomail.com",
                    "senha": "123456"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Bad Request"
          },
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Produtos": {
        "type": "object",
        "properties": {
          "produto": {
            "type": "string"
          },
          "descricao": {
            "type": "string"
          },
          "foto": {
            "type": "string"
          },
          "preco": {
            "type": "number"
          }
        }
      },
      "Usuarios": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "nome": {
            "type": "string"
          },
          "senha": {
            "type": "string"
          },
          "adm": {
            "type": "boolean"
          }
        }
      },
      "Login": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "senha": {
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {
      "token": {
        "type": "apiKey",
        "in": "header",
        "name": "Authorization"
      }
    }
  }
}
